organigrama/core/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    #Personales
    url(r'^$', views.home, name='home'),
    url(r'^(?P<origen_id>\d+)$', views.home, name='home'),
    path('origen/<int:padre_id>/max/<int:max_child>/', views.home_limit, name='home_limit'),

    #Generar Listado
    path('lista', views.home_listado, name='home_pdf'),
    path('lista_edit', views.home_listado, name='home_pdf'),

    #Edicion
    path('crear_hijo/<int:id_padre>/', views.crear_sub_org, name='crear_sub_org'),
    
    #Web Services
    path('ws_org/', views.ws_org, name='ws_org'),
    path('ws_org/origen/<int:padre_id>/max/<int:max_child>/', views.ws_org_max, name='ws_org_max'),
    path('ws_func/', views.ws_func, name='ws_func'),
]

organigrama/organigrama/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

#Definimos todas nuestras urls
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),

    #Proyectos Propios
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organigrama/core/models.py
from __future__ import unicode_literals

from django.db import models
from tinymce.models import HTMLField
from django.core.files.storage import FileSystemStorage

from datetime import datetime, date
#Import personales
from organigrama.settings import MEDIA_URL

#Choice Field
JERARQUIA = ((0, 'Sin Jerarquia'),
            (10, 'Poder Gubernamental'),
            (20, 'Gobernacion'),
            (30, 'Ministerio'),(31, 'Secretaria'),(32, 'SubSecretaria'),(33, 'Direccion'),(34, 'Coordinacion'),
            (40, 'Legislativo'),
            (50, 'Judicial'),
            (60, 'Municipio'),(61, 'Intendencia'),(62, 'Consejo'),
            (70, 'Escleciastico'),
            (80, 'Privados'),
            )

CARGOS =    ((0, 'Sin Cargo'),
            (1, 'Gobernador'), (2, 'Vice Gobernador'),
            (10, 'Ministro'),
            (20, 'Secretario'), (21, 'Secretaria'), (22, 'Subsecretario'), (23, 'SubScretaria'),
            (31, 'Director'), (32, 'Directora'), (33, 'SubDirector'), (34, 'SubDirectora'), 
            (41, 'Coordinador'), (42, 'Coordinadora'),
            (51, 'Consejal'), (52, 'Diputado'), (53, 'Senador'), (54, 'Diputada'), (55, 'Senadora'),
            (61, 'Juez'), (62, 'Fiscal'), (63, 'Vocal'), (64, 'Procurador'), (65, 'Procuradora'), (66, 'Defensor'),
            (71, 'Intendente'), (72, 'Comisionado'),
            (81, 'Escribano'), (82, 'Presidente'), (83, 'Vice Presidente'),
            (91, 'Administrativo'), (92, 'Jefe'), (93, 'Obispo'), (94, 'Sacerdote'), (95, 'Parroco'), (97, 'Consul'), (99, 'Asesor'))

# Create your models here.
class Organismo(models.Model):
    padre = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True, related_name='hijos')
    nombre = models.CharField('Titulo', max_length=200)
    jerarquia = models.IntegerField(choices=JERARQUIA, default=0)
    descripcion = HTMLField(blank=True, null=True)
    icono = models.ImageField(storage=FileSystemStorage(location=MEDIA_URL), blank=True, null=True)
    direccion = models.CharField('Direccion', max_length=200, blank=True, null=True)
    cuit = models.CharField('CUIT', max_length=13, blank=True, null=True)
    telefonos = models.CharField('Telefonos', max_length=100, blank=True, null=True)
    web = models.URLField('Web', blank=True, null=True)
    color = models.CharField(max_length=7, default="#ffffff")
    activo = models.BooleanField(default=True)
    visible = models.BooleanField(default=True)
    def __str__(self):
        if self.padre is not None:
            return self.nombre + ' > ' + self.padre.nombre
        else:
            return self.nombre + ' (Sin Asignar)'
    def as_dict(self):
        if self.padre is None:
            self.padre = self
        return {
            "id": self.id,
            "nombre": self.nombre,
            "padre": self.padre.id,
        }
    def funcionario_actual(self):
        return self.funcionarios.filter(activo=True)

class Funcionario(models.Model):
    organismo = models.ForeignKey(Organismo, on_delete=models.SET_NULL, related_name='funcionarios', blank=True, null=True)
    cargo = models.IntegerField(choices=CARGOS, default=0)
    subcargo = models.CharField('SubCargo', max_length=20, blank=True, null=True)
    funcion_unica = models.BooleanField(default=False)
    nombres = models.CharField('Nombres', max_length=100)
    apellidos = models.CharField('Apellidos', max_length=100)
    foto = models.ImageField(storage=FileSystemStorage(location=MEDIA_URL), blank=True, null=True)
    dni = models.CharField('DNI', max_length=100, blank=True, null=True)
    titulo = models.CharField('Titulo Profesional', max_length=20)
    email = models.EmailField('Correo Personal', blank=True, null=True)
    telefono = models.CharField('Telefono', max_length=20, blank=True, null=True)
    decreto = models.IntegerField(blank=True, null=True)
    begda = models.DateField('Designacion',  default=date(2019, 1, 1))
    endda = models.DateField('Cese de Funciones', default=date(9999, 12, 31))
    activo = models.BooleanField(default=True)
    def __str__(self):
        if self.organismo is None: 
            return 'Sin Organismo > ' + self.nombres + ' ' + self.apellidos
        else:
            return self.organismo.nombre + ' > ' + self.nombres + ' ' + self.apellidos
    def as_dict(self):
        return {
            "organismo": self.organismo.id,
            "nombres": self.nombres,
            "apellidos": self.apellidos,
            "cargo": dict(CARGOS).get(self.cargo),
            "dni": self.dni,
        }
    def save(self, *args, **kwargs):
        if self.activo == True and self.funcion_unica:#tener en cuenta otros funcionarios
            self.organismo.funcionarios.exclude(pk=self.pk).filter(cargo=self.cargo,subcargo=self.subcargo).update(endda=self.begda, activo=False)
        super(Funcionario, self).save(*args, **kwargs)

organigrama/core/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime, date, timedelta
from django.core import serializers
from django.views.generic import View
from django.utils import timezone

#Import Personales
from .models import Organismo, Funcionario


# Create your views here.
def home(request, origen_id=None):
    if origen_id is None:
        origen = Organismo.objects.filter(padre=None, activo=True).order_by('id').first()
    else:
        origen = Organismo.objects.get(id=origen_id, activo=True)
    return render(request, 'home.html', {'origen': origen, })

def home_limit(request, padre_id, max_child):
    origen = Organismo.objects.get(id=padre_id)
    return render(request, 'home_limit.html', {'origen': origen, 'max_child': max_child})

def home_listado(request):
    origen = Organismo.objects.filter(padre=None, activo=True).order_by('id').first()
    fecha = timezone.now()
    if request.path_info == "/lista":
        edit = False
    else:
        edit = True
    print(request.path_info)
    return render(request, 'lista/lista.html', {'origen': origen, 'editable': edit, 'fecha': fecha, })

def crear_sub_org(request, id_padre):
    new_org = Organismo()
    new_org.padre = Organismo.objects.get(pk=id_padre)
    new_org.nombre = 'SubOrganismo'
    new_org.save()
    return HttpResponseRedirect('/admin/core/organismo/'+ str(new_org.id) + '/change/')

def ws_org(request):
    organismos = [org.as_dict() for org in Organismo.objects.filter(activo=True)]
    return HttpResponse(json.dumps({"data": organismos}), content_type='application/json')

def ws_org_max(request, padre_id, max_child):
    organismos = Organismo.objects.none()
    org_buscar = Organismo.objects.filter(id=padre_id)

    for x in range(max_child):
        organismos = organismos | org_buscar
        for org in org_buscar:
            org_buscar = org_buscar.exclude(id=org.id)
            org_buscar = org_buscar | Organismo.objects.filter(padre=org)

    organismos = organismos | org_buscar
    organismos = [org.as_dict() for org in organismos]#Lo convertimos en diccionario serialiable
    return HttpResponse(json.dumps({"data": organismos}), content_type='application/json')

def ws_func(request):
    funcionarios = [func.as_dict() for func in Funcionario.objects.filter(activo=True)]
    return HttpResponse(json.dumps({"data": funcionarios}), content_type='application/json')

organigrama/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Organigrama Gubernamental</title>

    {% load static %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/organigrama.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/pop_up.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/lista.css' %}" />
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
  </head>
  <body>
      <div class="popup-overlay"></div>
      {% block content %}
      
      {% endblock %}
      <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/pop_up.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/tabs.js' %}"></script>
      
  </body>
</html>

organigrama/core/templates/home.html
{% extends 'base.html' %}
    {% block content %}
        <div class="organigrama">
            <ul>
                {% include "nodo_arbol.html" with organismo=origen %}
            </ul>
        </div>
        {% endblock %}

organigrama/core/templates/home_limit.html
{% extends 'base.html' %}
    {% block content %}
        <div class="organigrama">
            <ul>
                {% include "nodo_arbol_limit.html" with organismo=origen max_child=max_child count=1 %}
            </ul>
        </div>
        {% endblock %}

organigrama/core/templates/lista/header.html
{% load static %}

{% block content %}
    <div class="header">
        <img src="{% static 'img/hornacal.jpg' %}" alt="(Edit)" class="imagen_header">
        <div class="header_titulo">
            <h1>Nomina Provincial</h1>
        </div>
        <div class="header_encabezado">
            <p >Fecha: {{ fecha | date:"d/m/Y" }}</p>
        </div>
        <div class="header_logo">
            <img src="{% static 'img/jujuy.png' %}" alt="(Edit)">
        </div>
    </div>
    <p><a class="derecha" href="" onclick="Imprimir()">(Imprimir Nomina)</a></p>
    <br>
    {% if user.is_staff %}
        {% if editable %}
            <p><a class="derecha" href="/lista">Ir a version normal</a></p>
        {% else %}    
            <p><a class="derecha" href="/lista_edit">Ir a version editable</a></p>
        {% endif %}
    {% endif %}
{% endblock %}

organigrama/core/templates/lista/lista.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Nomina Provincial</title>
        {% load static %}
        <link rel="icon" href="{% static 'img/favicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/lista.css' %}" />
    </head>
    <body>
        {% include "lista/header.html" with fecha=fecha %}
        <div class="listado">
            {% include "lista/nodo_lista.html" with organismo=origen editable=editable %}
        </div>
    </body>


    <script>
        function Imprimir() {
        window.print();
        }
    </script>
</html>

organigrama/core/templates/lista/nodo_lista.html
{% load static %}

{% block content %}
    {% if organismo.activo and organismo.visible %}
        <div class="organismo" style="background-image: linear-gradient(to bottom right, {{organismo.color}} , white);">
            <div class="institucional">
                <p>
                    <b>{{organismo.nombre}}</b>
                    {% if editable %}
                        <a class="clean" target="_blank" href="/admin/core/organismo/{{ organismo.id }}/change/">
                            <img src="/static/img/edit_icon.png" alt="(Edit)" class="icono">  
                        </a>
                    {% endif %}
                </p>
                {% if organismo.direccion %}<p>Direccion: {{organismo.direccion}}</p>{% endif %}
                {% if organismo.telefonos %}<p>Telefonos: {{organismo.telefonos}}</p>{% endif %}
                {% if organismo.web %}<p><a href="{{organismo.web}}">Pagina Web</a></p>{% endif %}
            </div>
            <div class="funcionarios">
                {% include "mostrar_funcionario.html" with organismo=organismo %}
            </div>
            {% if organismo.hijos.exists %}
                {% for org_hijo in organismo.hijos.all %}
                    {% include "lista/nodo_lista.html" with organismo=org_hijo edit=edit %}
                {% endfor %}
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

organigrama/core/templates/mostrar_funcionario.html
{% load static %}

{% block content %}
    {% with funcionarios=organismo.funcionario_actual %}
        {% for funcionario in funcionarios %}
            <div class="funcionario">
                {% if funcionario.foto %}
                    <div class="funcionario_foto">
                            <img src="/{{funcionario.foto.url}}" alt="(foto)" class="img_funcionario">      
                    </div>
                {% endif %}
                <div class="funcionario_info">
                    <p>
                        <b>{{funcionario.get_cargo_display}}:</b> {{funcionario.titulo}} {{funcionario.apellidos}}, {{funcionario.nombres}}
                        {% if editable %}
                            <a class="clean" target="_blank" href="/admin/core/funcionario/{{ funcionario.id }}/change/">
                                <img src="{% static 'img/edit_icon.png' %}" alt="(Edit)" class="icono">
                            </a>
                        {% endif %}
                    </p>
                    <p>{% if funcionario.telefono %}<b>Telefono:</b>{{funcionario.telefono}}{%endif%}</p>
                    <p>{% if funcionario.email %}<b>Email:</b>{{funcionario.email}}{%endif%}</p>
                </div>
            </div>
        {% endfor %}
    {% endwith %}
{% endblock %}

organigrama/core/templates/mostrar_organismo.html
        <div class="popup">
            <a class "a_org">{{ organismo.nombre }}</a>
            <div class="popuptext">
                <div class="tab">
                    <button class="tablinks" onclick="openTab(event, 'Organismo-{{organismo.id}}')">Organismo</button>
                    <button class="tablinks" onclick="openTab(event, 'Funcionarios-{{organismo.id}}')">Funcionarios</button>
                    {% if user.is_staff %}
                        <button class="tablinks" onclick="openTab(event, 'Admin-{{organismo.id}}')">Administracion</button>
                    {% endif %}
                </div>

                <div id="Organismo-{{organismo.id}}" class="tabcontent">
                    {% if organismo.icono %} <img class = "img_logo" src="/{{ organismo.icono.url }}" >{% endif %}
                    <div class="clean"><h2><a href='/{{organismo.id}}'>{{ organismo.nombre }}</a></h2></div>
                    <div class="clean">{{ organismo.descripcion|safe }}</div>
                    <h3> Informacion Util:</h3>
                    <p><b>Direccion:</b> {{ organismo.direccion }}</p>
                    <p><b>Telefonos:</b> {{ organismo.telefonos }}</p>
                    <a class="clean" target="_blank" href="{{ organismo.web }}"><b>Pagina Web</b></a>
                </div>
                
                <div id="Funcionarios-{{organismo.id}}" class="tabcontent">
                    <h2>Funcionarios</h2>
                    <div class="funcionarios" style="width: 100%">
                        {% include "mostrar_funcionario.html" with organismo=organismo %}
                    </div>
                </div>
                
                <div id="Admin-{{organismo.id}}" class="tabcontent">
                    {% if user.is_staff %}
                        <p class="clean">Modificar organismo o funcionarios</p>
                            <a class="clean" target="_blank" href="/admin/core/organismo/{{ organismo.id }}/change/">
                                <img class = "img_icon" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                            </a>
                        </p>
                        
                        <p class="clean">Crear SubOrganismo</p>
                            <a class="clean" target="_blank" href="/crear_hijo/{{ organismo.id }}">
                                <img class = "img_icon" src="/static/admin/img/icon-addlink.svg" alt="Agregar SubOrganismo">
                            </a>
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>

organigrama/core/templates/nodo_arbol.html
{% block content %}
    <li>
        {% include "mostrar_organismo.html" with organismo=organismo %}
        {% if organismo.hijos.exists %}
            <ul>
                {% for org_hijo in organismo.hijos.all %}
                    {% include "nodo_arbol.html" with organismo=org_hijo %}
                {% endfor %}
            </ul>
        {% endif %}
    </li>
{% endblock %}

organigrama/core/templates/nodo_arbol_limit.html
{% block content %}
    <li>
        {% include "mostrar_organismo.html" with organismo=organismo %}

        {% if organismo.hijos.exists %}
            {% ifnotequal max_child count  %}
                <ul>
                    {% for org_hijo in organismo.hijos.all %}
                        {% include "nodo_arbol_limit.html" with organismo=org_hijo max_child=max_child count=count|add:1 %}
                    {% endfor %}
                </ul>
            {% endifnotequal %}
        {% endif %}
    </li>
{% endblock %}

organigrama/core/templates/pdf/header.html
{% load static %}

{% block content %}
    <div class="header">
        <img src="{% static 'img/hornacal.jpg' %}" alt="(Edit)" class="imagen_header">
        <div class="header_titulo">
            <h1>Nomina Provincial</h1>
        </div>
        <div class="header_encabezado">
            <p >Fecha: {{ fecha | date:"d/m/Y" }}</p>
        </div>
        <div class="header_logo">
            <img src="{% static 'img/jujuy.png' %}" alt="(Edit)">
        </div>
    </div>
    {% if user.is_staff %}
        {% if editable %}
            <a class="derecha" href="/lista">Ir a version normal</a>
        {% else %}    
            <a class="derecha" href="/lista_edit">Ir a version editable</a>
        {% endif %}
    {% endif %}
{% endblock %}

organigrama/core/templates/pdf/nodo_pdf.html
{% load static %}

{% block content %}
    {% if organismo.activo and organismo.visible %}
        <div class="organismo">
            <div class="institucional">
                <p>
                    <b>{{organismo.nombre}}</b>
                    {% if editable %}
                        <a class="clean" target="_blank" href="/admin/core/organismo/{{ organismo.id }}/change/">
                            <img src="/static/img/edit_icon.png" alt="(Edit)" class="icono">  
                        </a>
                    {% endif %}
                </p>
                <p>Direccion: {{organismo.direccion}}</p>
                <p>Telefonos: {{organismo.telefonos}}</p>
                {% if organismo.web %}<p><a href="{{organismo.web}}">Pagina Web</a></p>{% endif %}
            </div>
            <div class="funcionarios">
                {% for funcionario in organismo.funcionarios.all %}
                    {% if funcionario.activo %}
                        <div class="funcionario">
                            {% if funcionario.foto %}
                                <div class="funcionario_foto">
                                        <img src="/{{funcionario.foto.url}}" alt="(foto)" class="img_funcionario">      
                                </div>
                            {% endif %}
                            <div class="funcionario_info">
                                <p>
                                    <b>{{funcionario.get_cargo_display}}:</b> {{funcionario.titulo}} {{funcionario.apellidos}}, {{funcionario.nombres}}
                                    {% if editable %}
                                        <a class="clean" target="_blank" href="/admin/core/funcionario/{{ funcionario.id }}/change/">
                                            <img src="{% static 'img/edit_icon.png' %}" alt="(Edit)" class="icono">
                                        </a>
                                    {% endif %}
                                </p>
                                <p>{% if funcionario.telefono %}<b>Telefono:</b>{{funcionario.telefono}}{%endif%}</p>
                                <p>{% if funcionario.email %}<b>Email:</b>{{funcionario.email}}{%endif%}</p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            {% if organismo.hijos.exists %}
                {% for org_hijo in organismo.hijos.all %}
                    {% include "pdf/nodo_pdf.html" with organismo=org_hijo edit=edit %}
                {% endfor %}
            {% endif %}
        </div>
    {% endif %}
{% endblock %}